name = "rv0-production"
compatibility_date = "2024-12-01"

[env.production]
name = "rv0-prod"

[[pages_build_output_dir]]
value = "out"

[pages.build]
command = "npm run build"

[pages.env_vars]
RASTERVECTOR_API_URL = "https://rastervector-n6ofijmqgq-uc.a.run.app"